apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApp-deployment
  labels:
    app: MyApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: MyApp
        image: yklain/MyApp:v1
        ports:
        - containerPort: 8000
